
   <!-- MENU SIDEBAR-->
        
   <?php
       
       include('../partials/sidebar.php');
       
       ?>


        <!-- END MENU SIDEBAR-->

        <!-- PAGE CONTAINER-->
        <div class="page-container">
            <!-- HEADER DESKTOP-->
           <?php
           
           include '../partials/navbar.php';
           
           
           
           ?>








<div class="main-content ">
                <div class="section__content section__content--p30">



                </div>
            </div>